Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'powersystem_ui')
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('power_ui', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

