Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'dsplib')
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('DSP', src, depend = [''], CPPPATH = CPPPATH)

Return('group')


